"""empty message

Revision ID: dab5a1a22daa
Revises: None
Create Date: 2016-05-06 11:15:54.327000

"""

# revision identifiers, used by Alembic.
revision = 'dab5a1a22daa'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('todo_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('todos', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('done', sa.Boolean(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_todo_list_description'), 'todo_list', ['description'], unique=False)
    op.create_index(op.f('ix_todo_list_timestamp'), 'todo_list', ['timestamp'], unique=False)
    op.create_index(op.f('ix_todo_list_todos'), 'todo_list', ['todos'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_todo_list_todos'), table_name='todo_list')
    op.drop_index(op.f('ix_todo_list_timestamp'), table_name='todo_list')
    op.drop_index(op.f('ix_todo_list_description'), table_name='todo_list')
    op.drop_table('todo_list')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    ### end Alembic commands ###
